"""initial

Revision ID: f037fe63e86e
Revises: 
Create Date: 2026-08-11 13:01:50.233145
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import PortableJSON


revision: str = 'f037fe63e86e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('place_id', sa.String(length=200), nullable=True),
    sa.Column('coordinates', PortableJSON(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=False),
    sa.Column('top_attractions', PortableJSON(), nullable=True),
    sa.Column('top_restaurants', PortableJSON(), nullable=True),
    sa.Column('neighborhoods', PortableJSON(), nullable=True),
    sa.Column('route_templates', PortableJSON(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_baselines_key'), 'destination_baselines', ['key'], unique=True)
    op.create_table('flight_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_key', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('departure_date', sa.String(length=10), nullable=False),
    sa.Column('flight_data', PortableJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_cache_expires_at'), 'flight_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_flight_cache_search_key'), 'flight_cache', ['search_key'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_location', sa.String(length=300), nullable=True),
    sa.Column('cities', PortableJSON(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('travel_type', sa.String(length=100), nullable=True),
    sa.Column('budget', PortableJSON(), nullable=True),
    sa.Column('budget_mode', sa.String(length=20), nullable=True),
    sa.Column('generated_itinerary', PortableJSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('tags', PortableJSON(), nullable=True),
    sa.Column('is_upcoming', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('trip_start_date', sa.Date(), nullable=True),
    sa.Column('trip_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', PortableJSON(), nullable=True),
    sa.Column('google_tokens', PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('messages', PortableJSON(), nullable=True),
    sa.Column('metadata', PortableJSON(), nullable=True),
    sa.Column('itinerary', PortableJSON(), nullable=True),
    sa.Column('trip_state', PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_flight_cache_search_key'), table_name='flight_cache')
    op.drop_index(op.f('ix_flight_cache_expires_at'), table_name='flight_cache')
    op.drop_table('flight_cache')
    op.drop_index(op.f('ix_destination_baselines_key'), table_name='destination_baselines')
    op.drop_table('destination_baselines')
    # ### end Alembic commands ###
